// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_hZx9HpPMcasNm8QAXJIbBdXlInYfes',
    appId: '1:172697834788:web:32adcc3d957de9b8214fb1',
    messagingSenderId: '172697834788',
    projectId: 'chatapp-d4407',
    authDomain: 'chatapp-d4407.firebaseapp.com',
    databaseURL: 'https://chatapp-d4407-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-d4407.appspot.com',
    measurementId: 'G-S3Q75GK9S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYu-aqeTgrFfQDNd8rNSov2IxrjTWjwks',
    appId: '1:172697834788:android:0eb35a48926187f6214fb1',
    messagingSenderId: '172697834788',
    projectId: 'chatapp-d4407',
    databaseURL: 'https://chatapp-d4407-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-d4407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ZRsiH3d2t-wLhJHE4gEzuWD8GFC9sI0',
    appId: '1:172697834788:ios:83863478fc4096db214fb1',
    messagingSenderId: '172697834788',
    projectId: 'chatapp-d4407',
    databaseURL: 'https://chatapp-d4407-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-d4407.appspot.com',
    androidClientId: '172697834788-g1ipja3sq16uobhsqhnr3hs0287vb115.apps.googleusercontent.com',
    iosClientId: '172697834788-6i9falan48rg10lp2ef2trugsnf8mnlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ZRsiH3d2t-wLhJHE4gEzuWD8GFC9sI0',
    appId: '1:172697834788:ios:83863478fc4096db214fb1',
    messagingSenderId: '172697834788',
    projectId: 'chatapp-d4407',
    databaseURL: 'https://chatapp-d4407-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-d4407.appspot.com',
    androidClientId: '172697834788-g1ipja3sq16uobhsqhnr3hs0287vb115.apps.googleusercontent.com',
    iosClientId: '172697834788-6i9falan48rg10lp2ef2trugsnf8mnlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
